In [ ]:
import numpy as np
empty_array = np.empty((2, 2))
print(empty_array)
ones_array = np.ones((4, 2))
print(ones_array)
fill_value_array = np.full((3, 3), 7)
print(fill_value_array)
example_array = np.array([[5, 6], [7, 8]])
zeros_like_array = np.zeros_like(example_array)
print(zeros_like_array)
ones_like_array = np.ones_like(example_array)
print(ones_like_array)
new_list = [1, 2, 3, 4]
converted_array = np.array(new_list)
print(converted_array)

[[4.93089396e-310 0.00000000e+000]
 [            nan 2.73610137e-310]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[0 0]
 [0 0]]
[[1 1]
 [1 1]]
[1 2 3 4]


In [ ]:
import numpy as n
array_10_to_49 = np.arange(10, 50)
print("Task 1:\n", array_10_to_49)

matrix_0_to_8 = np.arange(9).reshape(3, 3)
print("\nTask 2:\n", matrix_0_to_8)


identity_matrix = np.eye(3)
print("\nTask 3:\n", identity_matrix)


random_array = np.random.random(30)
mean_random_array = random_array.mean()
print("\nTask 4:\nRandom array:\n", random_array)
print("Mean:", mean_random_array)

random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\nTask 5:\nRandom 10x10 array:\n", random_10x10)
print("Minimum value:", min_value)
print("Maximum value:", max_value)
zero_array = np.zeros(10)
zero_array[4] = 1
print("\nTask 6:\n", zero_array)

arr = [1, 2, 0, 0, 4, 0]
reversed_array = np.array(arr)[::-1]
print("\nTask 7:\n", reversed_array)

border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\nTask 8:\n", border_array)

checkerboard_matrix = np.zeros((8, 8))
checkerboard_matrix[1::2, ::2] = 1
checkerboard_matrix[::2, 1::2] = 1
print("\nTask 9:\n", checkerboard_matrix)

Task 1:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

Task 2:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Task 3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Task 4:
Random array:
 [0.60329772 0.98388562 0.16041352 0.23967856 0.49796227 0.82659008
 0.31204531 0.91546147 0.63264223 0.84270498 0.93707822 0.16393589
 0.17910892 0.11667385 0.30493586 0.84649546 0.89169039 0.30725115
 0.15711805 0.87919554 0.91821093 0.242338   0.81698091 0.83301533
 0.20809989 0.98877167 0.01029256 0.61338225 0.66078301 0.08825162]
Mean: 0.5392763755618055

Task 5:
Random 10x10 array:
 [[0.59244304 0.04376169 0.77437231 0.46386157 0.21045632 0.34764475
  0.99480187 0.96741157 0.98753043 0.15779648]
 [0.36027071 0.97019307 0.25558353 0.05968368 0.7404468  0.93263082
  0.11522008 0.3850885  0.54039448 0.86113487]
 [0.31444663 0.53890737 0.18365613 0.39985709 0.29505117 0.79969027
  0.83619252 0.98836065 0.56941669 0.32286552]
 [0.75435237 0.31000223

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

add_xy = x + y
print("Task 1: Add the two arrays\n", add_xy)


subtract_xy = x - y
print("\nTask 2: Subtract the two arrays\n", subtract_xy)


multiply_x = x * 3
print("\nTask 3: Multiply the array with an integer\n", multiply_x)


square_x = np.square(x)
print("\nTask 4: Square of each element of the array\n", square_x)

dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("\nTask 5: Dot products")
print("Dot product of v and w:", dot_vw)
print("Dot product of x and v:\n", dot_xv)
print("Dot product of x and y:\n", dot_xy)


concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_col = np.vstack((v, w))
print("\nTask 6: Concatenation")
print("Concatenate x and y along rows:\n", concat_xy_row)
print("Concatenate v and w along columns:\n", concat_vw_col)


print("\nTask 7: Attempt to concatenate x and v")
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print(concat_xv)
except ValueError as e:
    print("Error:", e)

    v_reshaped = v.reshape(1, -1)
    concat_xv_fixed = np.concatenate((x, v_reshaped), axis=0)
    print("After fixing dimensions:\n", concat_xv_fixed)

Task 1: Add the two arrays
 [[ 6  8]
 [10 13]]

Task 2: Subtract the two arrays
 [[-4 -4]
 [-4 -3]]

Task 3: Multiply the array with an integer
 [[ 3  6]
 [ 9 15]]

Task 4: Square of each element of the array
 [[ 1  4]
 [ 9 25]]

Task 5: Dot products
Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]

Task 6: Concatenation
Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
 [[ 9 10]
 [11 12]]

Task 7: Attempt to concatenate x and v
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
After fixing dimensions:
 [[ 1  2]
 [ 3  5]
 [ 9 10]]


In [ ]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])


A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print("Task 1: A * A^(-1) = I (Identity matrix)\n", I)


AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nTask 2: Prove AB != BA")
print("AB = \n", AB)
print("BA = \n", BA)


AB_T = np.transpose(AB)
B_T_A_T = np.dot(np.transpose(B), np.transpose(A))
print("\nTask 3: Prove (AB)^T = B^T * A^T")
print("Transpose of AB = \n", AB_T)
print("B^T * A^T = \n", B_T_A_T)


A_eq = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_eq = np.array([-1, -3, 9])

A_inv_eq = np.linalg.inv(A_eq)
X = np.dot(A_inv_eq, B_eq)
print("\nTask 4: Solve the system of equations using inverse method")
print("Solution using inverse method: X = ", X)

X_solve = np.linalg.solve(A_eq, B_eq)
print("\nSolution using np.linalg.solve(): X = ", X_solve)

Task 1: A * A^(-1) = I (Identity matrix)
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Task 2: Prove AB != BA
AB = 
 [[23 13]
 [51 29]]
BA = 
 [[36 44]
 [13 16]]

Task 3: Prove (AB)^T = B^T * A^T
Transpose of AB = 
 [[23 51]
 [13 29]]
B^T * A^T = 
 [[23 51]
 [13 29]]

Task 4: Solve the system of equations using inverse method
Solution using inverse method: X =  [ 2.  1. -2.]

Solution using np.linalg.solve(): X =  [ 2.  1. -2.]
